{
 "title": "my",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "lustre_filesystem_used_bytes/lustre_filesystem_capacity_bytes*100",
     "legendFormat": "{{filesystem}}"
    },
    {
     "expr": "lustre_metrics_last_scrape*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zauzeće Lustre",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lustre_filesystem_used_bytes/lustre_filesystem_capacity_bytes*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Zauzeće /home",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "filesystem_used_bytes/filesystem_capacity_bytes*100",
     "legendFormat": "{{filesystem}}"
    }
   ]
  },
  {
   "title": "Zauzeće prostora na disku po korisnicima",
   "type": "table",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "lustre_quota_usage_bytes", "legendFormat": "{{user}}" },
    { "expr": "lustre_quota_soft_limit_bytes", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Korisnici koji su prekoračili limit",
   "type": "table",
   "gridPos": { "h": 17, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "lustre_quota_usage_bytes", "legendFormat": "{{user}}" },
    { "expr": "lustre_quota_soft_limit_bytes", "legendFormat": "{{user}}" },
    {
     "expr": "(lustre_quota_usage_bytes - lustre_quota_soft_limit_bytes)\n> 0\nand\nlustre_quota_soft_limit_bytes > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}